[package]
name = "safefile-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "safefile"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
colored = "2.0"
indicatif = "0.18.3"
chrono = "0.4.42"

safefile = { path = "../core" }
